---
title: "&nbsp;"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.height = 8,
  fig.width = 12
)
```

# {.tabset .tabset-fade .tabset-pills}

## Enteric Diseases and Food-Borne Diseases

```{r enteric-diseases-and-food-borne-diseases}
targets::tar_read(create_enteric_monthly_table)
```

## Respiratory Diseases

```{r respiratory-diseases}
targets::tar_read(create_resp_monthly_table)
```

## Sexually Transmitted Infections (STIs) and Blood Borne Infections (BBIs)

```{r sexually-transmitted-infections-and-blood-borne-infections}
targets::tar_read(create_sti_monthly_table)
```

## Vaccine Preventable Diseases (VPDs)

```{r vaccine-preventable-diseases}
targets::tar_read(create_vpd_monthly_table)
```

## Vector-Borne and Zoonotic Diseases

```{r vector-borne-and-zoonotic-diseases}
targets::tar_read(create_vbz_monthly_table)
```

## Other Diseases

```{r other-diseases}
targets::tar_read(create_other_monthly_table)
```
